"""
Type stubs for SimpleCommKitPyMqttClient - Python bindings for SimpleCommKit MQTT
"""
from typing import Callable, Optional

def get_error_description(error_code: int) -> str: ...

class MqttReconnectSetting:
    min_delay_ms: int
    max_delay_ms: int
    delay_policy: int
    max_retry_cnt: int
    def __init__(self) -> None: ...

class MqttTlsSetting:
    ca_file: str
    ca_path: str
    crt_file: str
    key_file: str
    verify_peer: bool
    def __init__(self) -> None: ...

class MqttWillMessage:
    topic: str
    qos: int
    retain: bool
    @property
    def payload(self) -> bytes: ...
    @payload.setter
    def payload(self, data: bytes) -> None: ...
    def __init__(self) -> None: ...

class MqttClient:
    """MQTT client for connecting to a broker and publishing/subscribing to topics."""

    def __init__(self) -> None: ...

    def connect(self, host: str, port: int = 1883) -> bool: ...
    def connect_ssl(self, host: str, port: int = 8883) -> bool: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...

    def set_client_id(self, id: str) -> None: ...
    def set_auth(self, username: str, password: str) -> None: ...
    def set_will(self, will: MqttWillMessage) -> None: ...

    def set_ping_interval(self, seconds: int) -> None: ...
    def set_connect_timeout(self, ms: int) -> None: ...
    def set_reconnect(self, setting: MqttReconnectSetting) -> None: ...
    def disable_reconnect(self) -> None: ...

    def enable_tls(self, setting: MqttTlsSetting) -> bool: ...
    def enable_tls_default(self) -> bool: ...

    def publish(self, topic: str, data: bytes, qos: int = 0, retain: bool = False) -> int: ...
    def publish_text(self, topic: str, data: str, qos: int = 0, retain: bool = False) -> int: ...
    def subscribe(self, topic: str, qos: int = 0) -> int: ...
    def unsubscribe(self, topic: str) -> int: ...

    def set_callback_on_connected(self, callback: Callable[[], None]) -> None: ...
    def set_callback_on_disconnected(self, callback: Callable[[], None]) -> None: ...
    def set_callback_on_message(self, callback: Callable[[str, bytes], None]) -> None: ...
    def set_callback_on_error(self, callback: Callable[[int], None]) -> None: ...
